[config]

[config.wallpaper]
set = true
command = "swww img --transition-type random {{ image }}"

[templates.bat]
input_path = '~/.config/matugen/templates/bat.tmTheme'
output_path = '~/.config/bat/themes/matugen-bat-colors.tmTheme'
post_hook = 'bat cache --build'

[templates.btop]
input_path = '~/.config/matugen/templates/btop.theme'
output_path = '~/.config/btop/themes/matugen.theme'
post_hook = 'pkill -USR2 btop || true'

[templates.cava]
input_path = '~/.config/matugen/templates/cava-colors.ini'
output_path = '~/.config/cava/themes/matugen'
post_hook = 'pkill -USR1 cava'

[templates.ghostty]
input_path = '~/.config/matugen/templates/ghostty'
output_path = '~/.config/ghostty/themes/Matugen'
post_hook = 'pkill -SIGUSR2 ghostty'

[templates.gtk3]
input_path = '~/.config/matugen/templates/gtk-colors.css'
output_path = '~/.config/gtk-3.0/matugen-colors.css'
post_hook = 'gsettings set org.gnome.desktop.interface gtk-theme ""; gsettings set org.gnome.desktop.interface gtk-theme adw-gtk3-{{mode}}'

[templates.gtk4]
input_path = '~/.config/matugen/templates/gtk-colors.css'
output_path = '~/.config/gtk-4.0/matugen-colors.css'

[templates.hyprland]
input_path = '~/.config/matugen/templates/hyprland.conf'
output_path = '~/.config/hypr/themes/matugen-colors.conf'

[templates.kitty]
input_path = '~/.config/matugen/templates/kitty-colors.conf'
output_path = '~/.config/kitty/themes/Matugen.conf'
post_hook = "kitty +kitten themes --reload-in=all Matugen"

[templates.color-scheme]
input_path = '~/.config/matugen/templates/Matugen.colors'
output_path = '~/.local/share/color-schemes/Matugen.colors'
post_hook = 'systemctl --user restart plasma-xdg-desktop-portal-kde' # Apply changes to kde file picker

[templates.qt5ct]
input_path = '~/.config/matugen/templates/qtct-colors.conf'
output_path = '~/.config/qt5ct/colors/matugen.conf'

[templates.qt6ct]
input_path = '~/.config/matugen/templates/qtct-colors.conf'
output_path = '~/.config/qt6ct/colors/matugen.conf'

[templates.quickshell]
input_path = '~/.config/matugen/templates/quickshell.qml'
output_path = '~/.config/quickshell/Colors.qml'

[templates.starship]
input_path = '~/.config/matugen/templates/starship.toml'
output_path = '~/.config/starship.toml'

[templates.yazi]
input_path = '~/.config/matugen/templates/yazi.toml'
output_path = '~/.config/yazi/theme.toml'
