gui:
  tabWidth: 2
  skipAmendWarning: true
  sidePanelWidth: 0.25
  expandFocusedSidePanel: true
  expandedSidePanelWeight: 5
  useHunkModeInStagingView: false
  theme:
    defaultFgColor:
      - cyan
  showNumstatInFilesView: true
  nerdFontsVersion: "3"
  showBranchCommitHash: true
  showDivergenceFromBaseBranch: 'arrowAndNumber'

